wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743185255
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      4: 3.13.2
      5: 0.19.8
      8:
      - 5
      13: linux-x86_64
model_lr:
  desc: null
  value: 0.00019124930481486055
c_ee_to_obj:
  desc: null
  value: 0.5727231327074911
c_obj_to_target:
  desc: null
  value: 1.0315611376215876
c_direction:
  desc: null
  value: 1.1271441508216793
completion_reward:
  desc: null
  value: 8.146917517454304
num_episodes_per_update:
  desc: null
  value: 8
