wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743185270
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      4: 3.13.2
      5: 0.19.8
      8:
      - 5
      13: linux-x86_64
model_lr:
  desc: null
  value: 0.00017718336517805078
c_ee_to_obj:
  desc: null
  value: 0.7796627327463608
c_obj_to_target:
  desc: null
  value: 1.5049223735693134
c_direction:
  desc: null
  value: 0.3984298151401535
completion_reward:
  desc: null
  value: 4.0721372154427655
num_episodes_per_update:
  desc: null
  value: 1
