_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
c_direction:
    value: 0.5
c_ee_to_obj:
    value: 0.1
c_obj_to_target:
    value: 0.2
completion_reward:
    value: 10
model_lr:
    value: 0.0001
